/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#3525cd",
        secondary: "#5d5e5f",
        surface: "#e0e5ec",
        "on-surface": "#2d3748",
        "on-surface-variant": "#464555",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#c3c0ff",
        "primary-fixed": "#e2dfff",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#454747",
        "surface-bright": "#fcf8ff",
        "secondary-fixed-dim": "#c6c6c6",
        "surface-dim": "#dcd8e5",
        "tertiary-container": "#a44100",
        "on-secondary": "#ffffff",
        "outline-variant": "#c7c4d8",
        "inverse-primary": "#c3c0ff",
        "surface-tint": "#4d44e3",
        "surface-container": "#f0ecf9",
        "primary-container": "#4f46e5",
        "error": "#ba1a1a",
        "secondary-container": "#e2e2e2",
        "tertiary-fixed-dim": "#ffb695",
        "surface-container-high": "#eae6f4",
        "on-secondary-fixed": "#1a1c1c",
        "tertiary": "#7e3000",
        "inverse-on-surface": "#f3effc",
        "surface-container-low": "#f5f2ff",
        "on-primary": "#ffffff",
        "surface-variant": "#e4e1ee",
        "on-tertiary-fixed-variant": "#7b2f00",
        "inverse-surface": "#302f39",
        "surface-container-highest": "#e4e1ee",
        "on-primary-fixed": "#0f0069",
        "secondary-fixed": "#e2e2e2",
        "on-primary-container": "#dad7ff",
        "on-background": "#1b1b24",
        "on-error": "#ffffff",
        "tertiary-fixed": "#ffdbcc",
        "on-tertiary-container": "#ffd2be",
        "outline": "#777587",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#3323cc",
        "on-tertiary-fixed": "#351000",
        "on-secondary-container": "#636465",
        "background": "#fcf8ff",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "1.5rem",
        "2xl": "1.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        "container-max": "1200px",
        unit: "8px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Geist"],
        display: ["Geist"],
        "label-mono": ["JetBrains Mono"],
        "body-lg": ["Geist"],
        "headline-lg": ["Geist"],
        caption: ["Geist"],
        "body-md": ["Geist"],
      },
      fontSize: {
        display: ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-mono": ["14px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        caption: ["12px", { lineHeight: "1.4", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
